title: Henrique Alves – Front-end Engineer
email: henriquea@gmail.com
description: >
  I'm Henrique Alves, Front-end Engineer focused on UX design based in London, England.
baseurl: "/"
url: http://alves.im
github: https://github.com/henriquea/henriquea.github.io
permalink: /:categories/:title.html
markdown: kramdown
